<a href="https://colab.research.google.com/github/Hyemmingway/ai_teamplay/blob/main/KSL_YHM_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

데이터 불러오기

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


데이터 전처리하기

In [4]:
!pip install IPython
from IPython.display import Image

!pip install pyforest
!pip install mediapipe

import cv2
import mediapipe as mp
import time

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.6 MB 5.4 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [29]:
#이미지 불러오기 
img = Image.open("/content/drive/MyDrive/2022-2 ipynb/인공지능통계분석/num5 data/KSL/00_01/00_01.0001.jpg")
img.show()

In [30]:
#이미지 numpy로 바꾸기 
import numpy as np
from PIL import Image

img
img.show()

x = np.array(img)
print(x)
print(x.shape)

x_2 = np.asarray(img)
print(x_2)
print(x_2.shape)

[[[ 75  77  56]
  [ 74  79  57]
  [ 73  83  59]
  ...
  [220 206 203]
  [203 189 186]
  [207 194 188]]

 [[ 71  74  53]
  [ 71  76  54]
  [ 70  80  56]
  ...
  [178 164 163]
  [231 217 214]
  [209 196 190]]

 [[ 67  70  51]
  [ 67  72  52]
  [ 66  75  54]
  ...
  [121 105 105]
  [227 213 210]
  [216 202 199]]

 ...

 [[ 47  29  27]
  [ 46  28  26]
  [ 46  28  26]
  ...
  [ 16   3  20]
  [ 17   2  21]
  [ 17   2  21]]

 [[ 48  30  26]
  [ 48  30  26]
  [ 47  29  27]
  ...
  [ 16   3  20]
  [ 17   2  21]
  [ 17   2  21]]

 [[ 48  30  26]
  [ 48  30  26]
  [ 48  30  26]
  ...
  [ 16   3  20]
  [ 16   3  21]
  [ 17   2  23]]]
(256, 256, 3)
[[[ 75  77  56]
  [ 74  79  57]
  [ 73  83  59]
  ...
  [220 206 203]
  [203 189 186]
  [207 194 188]]

 [[ 71  74  53]
  [ 71  76  54]
  [ 70  80  56]
  ...
  [178 164 163]
  [231 217 214]
  [209 196 190]]

 [[ 67  70  51]
  [ 67  72  52]
  [ 66  75  54]
  ...
  [121 105 105]
  [227 213 210]
  [216 202 199]]

 ...

 [[ 47  29  27]
  [ 46  28  26]
  [ 46

In [35]:
#mediapipe python API에 가져온 이미지 파일 적용해보기
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

# For static images:
IMAGE_FILES = x_2
with mp_hands.Hands(
    static_image_mode=True,
    max_num_hands=2,
    min_detection_confidence=0.5) as hands:
  for idx, file in enumerate(IMAGE_FILES):
    # Read an image, flip it around y-axis for correct handedness output (see
    # above).
    image = cv2.flip(cv2.imread('/content/drive/MyDrive/2022-2 ipynb/인공지능통계분석/num5 data/KSL/00_01/00_01.0001.jpg'), 1)
    # Convert the BGR image to RGB before processing.
    results = hands.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

    # Print handedness and draw hand landmarks on the image.
    print('Handedness:', results.multi_handedness)
    if not results.multi_hand_landmarks:
      continue
    image_height, image_width, _ = image.shape
    annotated_image = image.copy()
    for hand_landmarks in results.multi_hand_landmarks:
      print('hand_landmarks:', hand_landmarks)
      print(
          f'Index finger tip coordinates: (',
          f'{hand_landmarks.landmark[mp_hands.HandLandmark.INDEX_FINGER_TIP].x * image_width}, '
          f'{hand_landmarks.landmark[mp_hands.HandLandmark.INDEX_FINGER_TIP].y * image_height})'
      )
      mp_drawing.draw_landmarks(
          annotated_image,
          hand_landmarks,
          mp_hands.HAND_CONNECTIONS,
          mp_drawing_styles.get_default_hand_landmarks_style(),
          mp_drawing_styles.get_default_hand_connections_style())
    cv2.imwrite(
        'pic00_01_0001' + str(idx) + '.png', cv2.flip(annotated_image, 1))
    # Draw hand world landmarks.
    if not results.multi_hand_world_landmarks:
      continue
    for hand_world_landmarks in results.multi_hand_world_landmarks:
      mp_drawing.plot_landmarks(
        hand_world_landmarks, mp_hands.HAND_CONNECTIONS, azimuth=5)


Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: None
Handedness: No

In [ ]:
IMAGE_FILES